/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SorteioRouteImport } from './routes/sorteio'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as FinalistasRouteImport } from './routes/finalistas'
import { Route as ArtilheiroRouteImport } from './routes/artilheiro'
import { Route as ApostasEspeciaisRouteImport } from './routes/apostas-especiais'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosIdRouteImport } from './routes/jogos.$id'

const SorteioRoute = SorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalistasRoute = FinalistasRouteImport.update({
  id: '/finalistas',
  path: '/finalistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtilheiroRoute = ArtilheiroRouteImport.update({
  id: '/artilheiro',
  path: '/artilheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApostasEspeciaisRoute = ApostasEspeciaisRouteImport.update({
  id: '/apostas-especiais',
  path: '/apostas-especiais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIdRoute = JogosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JogosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/finalistas': typeof FinalistasRoute
  '/jogos': typeof JogosRouteWithChildren
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/sorteio': typeof SorteioRoute
  '/jogos/$id': typeof JogosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/finalistas': typeof FinalistasRoute
  '/jogos': typeof JogosRouteWithChildren
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/sorteio': typeof SorteioRoute
  '/jogos/$id': typeof JogosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/finalistas': typeof FinalistasRoute
  '/jogos': typeof JogosRouteWithChildren
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/sorteio': typeof SorteioRoute
  '/jogos/$id': typeof JogosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/finalistas'
    | '/jogos'
    | '/participantes'
    | '/ranking'
    | '/sorteio'
    | '/jogos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/finalistas'
    | '/jogos'
    | '/participantes'
    | '/ranking'
    | '/sorteio'
    | '/jogos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/finalistas'
    | '/jogos'
    | '/participantes'
    | '/ranking'
    | '/sorteio'
    | '/jogos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApostasEspeciaisRoute: typeof ApostasEspeciaisRoute
  ArtilheiroRoute: typeof ArtilheiroRoute
  FinalistasRoute: typeof FinalistasRoute
  JogosRoute: typeof JogosRouteWithChildren
  ParticipantesRoute: typeof ParticipantesRoute
  RankingRoute: typeof RankingRoute
  SorteioRoute: typeof SorteioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sorteio': {
      id: '/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof SorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalistas': {
      id: '/finalistas'
      path: '/finalistas'
      fullPath: '/finalistas'
      preLoaderRoute: typeof FinalistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artilheiro': {
      id: '/artilheiro'
      path: '/artilheiro'
      fullPath: '/artilheiro'
      preLoaderRoute: typeof ArtilheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apostas-especiais': {
      id: '/apostas-especiais'
      path: '/apostas-especiais'
      fullPath: '/apostas-especiais'
      preLoaderRoute: typeof ApostasEspeciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$id': {
      id: '/jogos/$id'
      path: '/$id'
      fullPath: '/jogos/$id'
      preLoaderRoute: typeof JogosIdRouteImport
      parentRoute: typeof JogosRoute
    }
  }
}

interface JogosRouteChildren {
  JogosIdRoute: typeof JogosIdRoute
}

const JogosRouteChildren: JogosRouteChildren = {
  JogosIdRoute: JogosIdRoute,
}

const JogosRouteWithChildren = JogosRoute._addFileChildren(JogosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApostasEspeciaisRoute: ApostasEspeciaisRoute,
  ArtilheiroRoute: ArtilheiroRoute,
  FinalistasRoute: FinalistasRoute,
  JogosRoute: JogosRouteWithChildren,
  ParticipantesRoute: ParticipantesRoute,
  RankingRoute: RankingRoute,
  SorteioRoute: SorteioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
