/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as PalpitesParticipantesRouteImport } from './routes/palpites-participantes'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as FinalistasRouteImport } from './routes/finalistas'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as ArtilheiroRouteImport } from './routes/artilheiro'
import { Route as ApostasEspeciaisRouteImport } from './routes/apostas-especiais'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogosIndexRouteImport } from './routes/jogos.index'
import { Route as JogosIdRouteImport } from './routes/jogos.$id'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const PalpitesParticipantesRoute = PalpitesParticipantesRouteImport.update({
  id: '/palpites-participantes',
  path: '/palpites-participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalistasRoute = FinalistasRouteImport.update({
  id: '/finalistas',
  path: '/finalistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtilheiroRoute = ArtilheiroRouteImport.update({
  id: '/artilheiro',
  path: '/artilheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApostasEspeciaisRoute = ApostasEspeciaisRouteImport.update({
  id: '/apostas-especiais',
  path: '/apostas-especiais',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIndexRoute = JogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosIdRoute = JogosIdRouteImport.update({
  id: '/jogos/$id',
  path: '/jogos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/convite': typeof ConviteRoute
  '/finalistas': typeof FinalistasRoute
  '/noticias': typeof NoticiasRoute
  '/palpites-participantes': typeof PalpitesParticipantesRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/jogos/$id': typeof JogosIdRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/convite': typeof ConviteRoute
  '/finalistas': typeof FinalistasRoute
  '/noticias': typeof NoticiasRoute
  '/palpites-participantes': typeof PalpitesParticipantesRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/jogos/$id': typeof JogosIdRoute
  '/jogos': typeof JogosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apostas-especiais': typeof ApostasEspeciaisRoute
  '/artilheiro': typeof ArtilheiroRoute
  '/convite': typeof ConviteRoute
  '/finalistas': typeof FinalistasRoute
  '/noticias': typeof NoticiasRoute
  '/palpites-participantes': typeof PalpitesParticipantesRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/jogos/$id': typeof JogosIdRoute
  '/jogos/': typeof JogosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/convite'
    | '/finalistas'
    | '/noticias'
    | '/palpites-participantes'
    | '/participantes'
    | '/ranking'
    | '/jogos/$id'
    | '/jogos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/convite'
    | '/finalistas'
    | '/noticias'
    | '/palpites-participantes'
    | '/participantes'
    | '/ranking'
    | '/jogos/$id'
    | '/jogos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apostas-especiais'
    | '/artilheiro'
    | '/convite'
    | '/finalistas'
    | '/noticias'
    | '/palpites-participantes'
    | '/participantes'
    | '/ranking'
    | '/jogos/$id'
    | '/jogos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApostasEspeciaisRoute: typeof ApostasEspeciaisRoute
  ArtilheiroRoute: typeof ArtilheiroRoute
  ConviteRoute: typeof ConviteRoute
  FinalistasRoute: typeof FinalistasRoute
  NoticiasRoute: typeof NoticiasRoute
  PalpitesParticipantesRoute: typeof PalpitesParticipantesRoute
  ParticipantesRoute: typeof ParticipantesRoute
  RankingRoute: typeof RankingRoute
  JogosIdRoute: typeof JogosIdRoute
  JogosIndexRoute: typeof JogosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palpites-participantes': {
      id: '/palpites-participantes'
      path: '/palpites-participantes'
      fullPath: '/palpites-participantes'
      preLoaderRoute: typeof PalpitesParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finalistas': {
      id: '/finalistas'
      path: '/finalistas'
      fullPath: '/finalistas'
      preLoaderRoute: typeof FinalistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artilheiro': {
      id: '/artilheiro'
      path: '/artilheiro'
      fullPath: '/artilheiro'
      preLoaderRoute: typeof ArtilheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apostas-especiais': {
      id: '/apostas-especiais'
      path: '/apostas-especiais'
      fullPath: '/apostas-especiais'
      preLoaderRoute: typeof ApostasEspeciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/': {
      id: '/jogos/'
      path: '/jogos'
      fullPath: '/jogos/'
      preLoaderRoute: typeof JogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos/$id': {
      id: '/jogos/$id'
      path: '/jogos/$id'
      fullPath: '/jogos/$id'
      preLoaderRoute: typeof JogosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApostasEspeciaisRoute: ApostasEspeciaisRoute,
  ArtilheiroRoute: ArtilheiroRoute,
  ConviteRoute: ConviteRoute,
  FinalistasRoute: FinalistasRoute,
  NoticiasRoute: NoticiasRoute,
  PalpitesParticipantesRoute: PalpitesParticipantesRoute,
  ParticipantesRoute: ParticipantesRoute,
  RankingRoute: RankingRoute,
  JogosIdRoute: JogosIdRoute,
  JogosIndexRoute: JogosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
